name=BlinkLED
version=1.0.0
author=Clovis Fritzen <electronics@fritzenlab.net>
maintainer=Clovis Fritzen <electronics@fritzenlab.net>
sensor=no
category=Device Control
url=https://github.com/FritzenLab/BlinkLED-reusable-Arduino
architectures=*
includes=BlinkLED.h